name: deploy

on: 
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker sudo compose up -d 
      - run: docker compose exec sudo php composer install
      - run: docker compose exec sudo php symfony console doctrine:database:create --env=test
      - run: docker compose exec sudo php symfony console doctrine:schema:update --env=test --force
      - run: docker compose exec sudo php php bin/phpunit
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd nws-inventaire2.0 && sudo git pull"
      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd nws-inventaire2.0 && sudo docker compose up -d --build --force-recreate"