name: build

on: 
  push: 
    branches-ignore:
      - 'main'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker compose up -d 
      - run: sudo docker compose exec php composer install
      - run: sudo docker compose exec php symfony console doctrine:database:create --env=test
      - run: sudo docker compose exec php symfony console doctrine:schema:update --env=test --force
      - run: sudo docker compose exec php php bin/phpunit
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: login to github container regestry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push to github registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/ugorastell/inventaire:latest
          target: nws-inventaire2.0